spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gemini?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
